// TenantStatus enum is not generated by Prisma since it's a String field
// Define it locally to match the schema

export enum TenantStatus {
  PENDING = "PENDING",
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  OFFBOARDING = "OFFBOARDING",
  DELETED = "DELETED",
}

import { Tenant, Prisma } from "@prisma/client";

// Pagination options
export interface ListOptions {
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: "asc" | "desc";
  status?: TenantStatus;
}

// Create tenant input
export interface CreateTenantInput {
  name: string;
  displayName: string;
  domain?: string;
  settings?: Record<string, unknown>;
  limits?: Record<string, unknown>;
  ssoConfig?: Record<string, unknown>;
  status?: TenantStatus;
}

// Update tenant input
export interface UpdateTenantInput {
  displayName?: string;
  domain?: string;
  settings?: Record<string, unknown>;
  limits?: Record<string, unknown>;
  ssoConfig?: Record<string, unknown>;
  status?: TenantStatus;
}

// Tenant filter
export interface TenantFilter {
  status?: TenantStatus;
  domain?: string;
  search?: string;
  startDate?: Date;
  endDate?: Date;
}

// Tenant with computed statistics
export interface TenantWithStats extends Tenant {
  userCount: number;
  roleCount: number;
  policyCount: number;
  apiKeyCount: number;
  activeSessionCount: number;
}

// Audit trail entry for tenant
export interface TenantAuditEntry {
  tenantId: string;
  action: string;
  performedBy: string;
  timestamp: Date;
  changes: Record<string, { old: unknown; new: unknown }>;
}

export interface ITenantRepository {
  // CRUD operations
  create(data: CreateTenantInput): Promise<Tenant>;
  update(id: string, data: UpdateTenantInput): Promise<Tenant>;
  delete(id: string): Promise<void>;

  // Read operations
  findById(id: string): Promise<Tenant | null>;
  findByName(name: string): Promise<Tenant | null>;
  findByDomain(domain: string): Promise<Tenant | null>;

  // List operations
  list(
    options?: ListOptions & TenantFilter,
  ): Promise<{ tenants: Tenant[]; total: number }>;
  findByStatus(status: TenantStatus): Promise<Tenant[]>;

  // Lifecycle operations
  activate(id: string): Promise<Tenant>;
  suspend(id: string): Promise<Tenant>;
  startOffboarding(id: string): Promise<Tenant>;
  completeOffboarding(id: string): Promise<void>;

  // Domain operations
  verifyDomain(id: string, domain: string): Promise<Tenant>;
  removeDomain(id: string): Promise<Tenant>;

  // Configuration operations
  updateSettings(
    id: string,
    settings: Record<string, unknown>,
  ): Promise<Tenant>;
  updateLimits(id: string, limits: Record<string, unknown>): Promise<Tenant>;
  updateSSOConfig(
    id: string,
    ssoConfig: Record<string, unknown>,
  ): Promise<Tenant>;

  // Statistics
  getStatistics(id: string): Promise<TenantWithStats>;
  count(options?: TenantFilter): Promise<number>;

  // Activity tracking
  updateLastActivity(id: string): Promise<void>;

  // Audit operations
  getAuditTrail(
    id: string,
    startDate?: Date,
    endDate?: Date,
  ): Promise<TenantAuditEntry[]>;

  // Search operations
  search(
    query: string,
    options?: ListOptions,
  ): Promise<{ tenants: Tenant[]; total: number }>;

  // Bulk operations
  bulkUpdateStatus(ids: string[], status: TenantStatus): Promise<number>;
  bulkDelete(ids: string[]): Promise<number>;
}
