/**
 * ITenantRepository Interface
 * Database operations for tenant management
 */

/**
 * ITenantRepository Interface
 * Database operations for tenant management
 */

// TenantStatus enum is not generated by Prisma since it's a String field
// Define it locally to match the schema
export enum TenantStatus {
  PENDING = "PENDING",
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  OFFBOARDING = "OFFBOARDING",
  DELETED = "DELETED",
}

import { Tenant } from "@prisma/client";

/**
 * Tenant repository interface for database operations
 */
export interface ITenantRepository {
  /**
   * Create a new tenant
   * @param data Tenant creation data
   * @returns Created tenant
   */
  create(data: CreateTenantDTO): Promise<Tenant>;

  /**
   * Find tenant by ID
   * @param id Tenant ID
   * @returns Tenant or null
   */
  findById(id: string): Promise<Tenant | null>;

  /**
   * Find tenant by name
   * @param name Tenant name
   * @returns Tenant or null
   */
  findByName(name: string): Promise<Tenant | null>;

  /**
   * Find all tenants with optional filtering
   * @param filter Optional filter criteria
   * @returns List of tenants
   */
  findAll(filter?: TenantFilterDTO): Promise<Tenant[]>;

  /**
   * Update tenant
   * @param id Tenant ID
   * @param data Update data
   * @returns Updated tenant
   */
  update(id: string, data: UpdateTenantDTO): Promise<Tenant>;

  /**
   * Update tenant status
   * @param id Tenant ID
   * @param status New status
   * @returns Updated tenant
   */
  updateStatus(id: string, status: TenantStatus): Promise<Tenant>;

  /**
   * Soft delete tenant
   * @param id Tenant ID
   * @returns Deletion success
   */
  delete(id: string): Promise<boolean>;

  /**
   * Check if tenant exists
   * @param id Tenant ID
   * @returns Exists flag
   */
  exists(id: string): Promise<boolean>;

  /**
   * Count tenants by status
   * @param status Optional status filter
   * @returns Count
   */
  count(status?: TenantStatus): Promise<number>;
}

/**
 * Tenant creation data transfer object
 */
export interface CreateTenantDTO {
  /** Unique tenant name */
  name: string;
  /** Optional tenant settings */
  settings?: Record<string, unknown>;
  /** Initial status (defaults to ACTIVE) */
  status?: TenantStatus;
}

/**
 * Tenant update data transfer object
 */
export interface UpdateTenantDTO {
  /** New name (optional) */
  name?: string;
  /** New settings (optional) */
  settings?: Record<string, unknown>;
  /** New status (optional) */
  status?: TenantStatus;
}

/**
 * Tenant filter criteria
 */
export interface TenantFilterDTO {
  /** Filter by status */
  status?: TenantStatus;
  /** Pagination: page number (1-based) */
  page?: number;
  /** Pagination: items per page */
  limit?: number;
  /** Sort field */
  sortBy?: keyof Tenant;
  /** Sort order */
  sortOrder?: "asc" | "desc";
}

/**
 * Tenant with additional computed properties
 */
export interface TenantWithStats extends Tenant {
  /** Number of policies */
  policyCount: number;
  /** Number of users */
  userCount: number;
}
